# This section defines the file path for the datasets
file_paths:
  calibration:
    beacons: "Dataset/calibration/beacons/beacons_calibration.txt"
    gt: "Dataset/calibration/gt/gt_calibration.txt"
  
  mobility:
    use_case_1:
      run1:
        beacons: "Dataset/mobility/beacons/use-case 1/beacons_mobility_use-case1_run1.txt"
        gt: "Dataset/mobility/gt/use-case 1/gt_mobility_use-case1_run1.txt"
      run2:
        beacons: "Dataset/mobility/beacons/use-case 1/beacons_mobility_use-case1_run2.txt"
        gt: "Dataset/mobility/gt/use-case 1/gt_mobility_use-case1_run2.txt"
      run3:
        beacons: "Dataset/mobility/beacons/use-case 1/beacons_mobility_use-case1_run3.txt"
        gt: "Dataset/mobility/gt/use-case 1/gt_mobility_use-case1_run3.txt"
      run4:
        beacons: "Dataset/mobility/beacons/use-case 1/beacons_mobility_use-case1_run4.txt"
        gt: "Dataset/mobility/gt/use-case 1/gt_mobility_use-case1_run4.txt"

    use_case_2:
      run1:
        beacons: "Dataset/mobility/beacons/use-case 2/beacons_mobility_use-case2_run1.txt"
        gt: "Dataset/mobility/gt/use-case 2/gt_mobility_use-case2_run1.txt"
      run2:
        beacons: "Dataset/mobility/beacons/use-case 2/beacons_mobility_use-case2_run2.txt"
        gt: "Dataset/mobility/gt/use-case 2/gt_mobility_use-case2_run2.txt"
      run3:
        beacons: "Dataset/mobility/beacons/use-case 2/beacons_mobility_use-case2_run3.txt"
        gt: "Dataset/mobility/gt/use-case 2/gt_mobility_use-case2_run3.txt"
      run4:
        beacons: "Dataset/mobility/beacons/use-case 2/beacons_mobility_use-case2_run4.txt"
        gt: "Dataset/mobility/gt/use-case 2/gt_mobility_use-case2_run4.txt"

    use_case_3:
      run1:
        beacons: "Dataset/mobility/beacons/use-case 3/beacons_mobility_use-case3_run1.txt"
        gt: "Dataset/mobility/gt/use-case 3/gt_mobility_use-case3_run1.txt"
      run2:
        beacons: "Dataset/mobility/beacons/use-case 3/beacons_mobility_use-case3_run2.txt"
        gt: "Dataset/mobility/gt/use-case 3/gt_mobility_use-case3_run2.txt"
      run3:
        beacons: "Dataset/mobility/beacons/use-case 3/beacons_mobility_use-case3_run3.txt"
        gt: "Dataset/mobility/gt/use-case 3/gt_mobility_use-case3_run3.txt"
      run4:
        beacons: "Dataset/mobility/beacons/use-case 3/beacons_mobility_use-case3_run4.txt"
        gt: "Dataset/mobility/gt/use-case 3/gt_mobility_use-case3_run4.txt"


# This section defines the anchor parameters
anchors:
  - id: a6501
    coordinates: [ 0, 300, 230 ] # Anchor 6501 coordinates - in centimemeters
    alfa: 2.12 # Path-loss coefficent
    ref_coordinates: [ 120, 300, 110 ] # Reference coordinate - in centimemeters
  - id: a6502
    coordinates: [ 600, 0, 230 ] # Anchor 6502 coordinates - in centimemeters
    alfa: 2.78 # Path-loss coefficent
    ref_coordinates: [ 600, 120, 110 ] # Reference coordinate - in centimemeters
  - id: a6503
    coordinates: [ 1200, 300, 230 ] # Anchor 6503 coordinates - in centimemeters
    alfa: 2.75 # Path-loss coefficent
    ref_coordinates: [ 1080, 300, 110 ] # Reference coordinate - in centimemeters
  - id: a6504
    coordinates: [ 600, 600, 230 ] # Anchor 6504 coordinates - in centimemeters
    alfa: 2.86 # Path-loss coefficent
    ref_coordinates: [ 600, 480, 110 ] # Reference coordinate - in centimemeters

#This section defines the Kalman Filter parameters
kalman_filter:
  delta_T: 0.2 #sampling time
  A: [[1, 0.2, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0.2], [0, 0, 0, 1]] # State Transition Matrix (if the sampling time changes, modify this matrix)
  C: [[1, 0, 0, 0], [0, 0, 1, 0]] #Observation Matrix
  Q: [[8, 0, 0, 0], [0, 8, 0, 0], [0, 0, 8, 0], [0, 0, 0, 8]] # Initial Noise Covariance Matrix of the Process
  R_MLT: [[250, 0], [0, 250]] # MLT Measurement Noise
  R_AoA_RSSI: [[250, 0], [0, 250]] # AoA+RSSI Measurement Noise
  R_AoA_only: [[25, 0], [0, 25]] # AoA-only Measurement Noise
  P: [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]] #Initial Error Covariance


# This section defines some calibration scenario configurations
calibration:
 begin_X: 120 #position that the calibration points starts in X coordinates - in centimemeters
 end_X: 1080 #position that the calibration points ends in X coordinates - in centimemeters
 begin_Y: 120 #position that the calibration points starts in Y coordinates - in centimemeters
 end_Y: 480 #position that the calibration points ends in Y coordinates - in centimemeters
 Z_score: 2 # Z-score threshold limit to remove RSSI outliers.

#This section configires some additional resources
additional:
 x_grid_limit: [-2.00, 8.00] # X grid climite for plots - in meters
 y_grid_limit: [-2.00, 14.00] # Y grid climite for plots - in meters
 plot_first_path: True # Change this value if you want to plot the estimated path generated by the algorithms only in first run.
 plot_all_paths: False # Change this value if you want to plot the estimated path generated by the algorithms in all runs.
 plot_first_RSSI: True # Change this value if you want to plot the RSSI curve in the Calibration code for only the 6501 Anchor.
 plot_all_RSSI: False # Change this value if you want to plot the RSSI curve in the Calibration code for the all Anchors.
 plot_error_bargraph: True # Change this value if you want to plot the bargraph with the average distance errors.
 plot_CDF: True # Change this value if you want to plot the CDF for the average distance error.
 polarization: 2ndP # The polarization used